### PR TITLE
Add errors endpoint documentation page

### PR DESCRIPTION
**Pull request by poisa**
Added a new page to the docs for the `/errors` endpoint.

Note: **Do not merge** until D31939-code is deployed.

### CODE REVIEW

**Review by ebinnion — COMMENTED** [review]
A question I'll pose here since it affects the documentation:

Is there a compelling reason that the errors endpoint requires authentication? If we were to make the endpoint public, then that would also simplify this documentation a bit as well.

**Comment by poisa** [comment]
Consistency and in a _very_ (_very_) minor measure security. If partners have already implemented the API it's probably even faster for them to call up a new endpoint with their existing authentication. Regarding security: the less outside parties know about the errors we catch, the better, I think.

**Comment by ebinnion** [comment]
With regards to consistency, which I assume means, consistency in how we handle authentication, I would argue that this type of information itself is different than the rest of our endpoints since it doesn't allow managing plans nor retrieving information about users, sites, plans, etc. And since the information itself in this endpoint is different, then perhaps it's OK that the authentication is different as well.

In regards to security, I agree that it's a minor measure of security. But, I would imagine that if we didn't have this endpoint, that we'd likely just document the errors in this repository anyways.

**Comment by poisa** [comment]
The patch to make this publicly available is here: D34563-code
I'll update this PR to reflect this changes shortly.

**Review by ebinnion — APPROVED** [review]

**Pull request merged**
